FROM wordpress:{WP_VERSION}-php7.4-apache

#Add sudo in order to run wp-cli as the www-data user 
RUN apt-get -y update
RUN apt-get install -y sudo

#Add WP-CLI 
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \ 
chmod +x wp-cli.phar && \ 
mv wp-cli.phar /usr/local/bin/wp

WORKDIR /var/www/html/
RUN chown -R www-data:www-data .