version: '3.6'

services:
  #######################################
  # Application
  #######################################
  {DOMAIN_NAME}-php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
    container_name: {DOMAIN_NAME}-php
    volumes:
      - ./../app:/var/www/html/
    env_file: .env
    environment:
      VIRTUAL_HOST : ${VIRTUAL_HOST}
    restart: always

networks:
  default:
    name: dockerwp
    external: true
