version: '3.6'
services:
  nginx:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - '8080:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./conf.d:/etc/nginx/conf.d/
      - ssl-certs:/etc/nginx/certs:ro
      - ./logs:/var/log/nginx
    restart: always

  mkcert:
    image: aegypius/mkcert-for-nginx-proxy
    container_name: nginx-mkcert
    restart: unless-stopped
    volumes:
      - ssl-certs:/app/certs:rw
      - ./certs-root/:/app/ca:rw
      - ~/.mozilla/firefox:/root/.mozilla/firefox:rw
      - ~/.pki/nssdb:/root/.pki/nssdb:rw
      - ${CA_STORE:-/usr/local/share/ca-certificates}:/usr/local/share/ca-certificates
      - /var/run/docker.sock:/var/run/docker.sock:ro

  dozzle:
    image: amir20/dozzle:latest
    container_name: nginx-dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 7007:8080

networks:
  default:
    name: dockerwp
    external: true

volumes:
  ssl-certs:
    name: ssl-certs
    external: true
