version: '3.6'
services:
  nginx:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - '8080:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./conf.d:/etc/nginx/conf.d/
      - ssl-certs:/etc/nginx/certs:ro
      - ./logs:/var/log/nginx
    restart: always

  mkcert:
    image: aegypius/mkcert-for-nginx-proxy
    container_name: nginx-mkcert
    restart: unless-stopped
    volumes:
      - ssl-certs:/app/certs:rw
      - ./certs-root/:/app/ca:rw
      - ~/.mozilla/firefox:/root/.mozilla/firefox:rw
      - ~/.pki/nssdb:/root/.pki/nssdb:rw
      - ${CA_STORE:-/usr/local/share/ca-certificates}:/usr/local/share/ca-certificates
      - /var/run/docker.sock:/var/run/docker.sock:ro

  nginx-db:
    image: mariadb
    container_name: nginx-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    restart: unless-stopped
    volumes:
      - ./../db/init-scripts:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: nginx-phpmyadmin
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=${PMA_VIRTUAL_HOST}
      - PMA_ABSOLUTE_URI=${PMA_ABSOLUTE_URI}
      - PMA_ARBITRARY=${PMA_ARBITRARY}
      - PMA_HOST=${PMA_HOST}
      - PMA_PORT=${PMA_PORT}
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
    restart: unless-stopped

networks:
  default:
    name: dockerwp
    external: true

volumes:
  ssl-certs:
    name: ssl-certs
    external: true
