version: "3.6"
services:
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    environment:
      - NGROK_AUTH=${NGROK_AUTH:-nan}
      - NGROK_REGION=${NGROK_REGION:-eu}
      - NGROK_BINDTLS=${NGROK_BINDTLS:-true}
    env_file: .env
    ports:
      - "4040:4040"
    command:
      - "start"
      - "--all"
      - "--config"
      - "/home/ngrok/.ngrok2/ngrok.yml"
    volumes:
      - ./.ngrok2/:/home/ngrok/.ngrok2/:rw
    restart: always

networks:
  default:
    name: dockerwp
    external: true


