version: "3"
services:
  #######################################
  # Backend | Directus
  #######################################
  {DOMAIN_NAME}-directus:
    container_name: {DOMAIN_NAME}-directus
    build: 
      context: ../
      dockerfile: docker/Dockerfile.backend
      args:
        DIRECTUS_VERSION: ${DIRECTUS_VERSION}
    volumes:
      - ./../backend/uploads:/directus/uploads
      - ./../backend/extensions:/directus/extensions
    environment:
      VIRTUAL_PORT: 8055
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      KEY: ${KEY}
      SECRET: ${SECRET}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      DB_CLIENT: ${DB_CLIENT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT_DOCKER}
      DB_DATABASE: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    depends_on:
      - {DOMAIN_NAME}-postgres
    restart: unless-stopped

  #######################################
  # Database
  #######################################
  {DOMAIN_NAME}-postgres:
    container_name: {DOMAIN_NAME}-postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - {DOMAIN_NAME}_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  #######################################
  # pgAdmin
  #######################################
  {DOMAIN_NAME}-pgadmin:
    image: dpage/pgadmin4:8.2
    container_name: {DOMAIN_NAME}-pgadmin
    environment:
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: ${DB_VIRTUAL_HOST}
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    depends_on:
      - {DOMAIN_NAME}-postgres
    restart: unless-stopped

networks:
  default:
    name: dockerwp
    external: true

volumes:
  {DOMAIN_NAME}_db_data:
