# default version if empty 
ARG DIRECTUS_VERSION=10.8.2

FROM directus/directus:${DIRECTUS_VERSION}

USER root
RUN corepack enable \
  && corepack prepare pnpm@8.9.0 --activate

EXPOSE 80

USER node
RUN pnpm install directus-extension-api-viewer
