version: "3"
services:
  #######################################
  # Backend | Directus
  #######################################
  {DOMAIN_NAME}-directus:
    container_name: {DOMAIN_NAME}-directus
    build: 
      context: ../
      dockerfile: docker/Dockerfile.backend
    volumes:
      - ./../backend/uploads:/directus/uploads
      - ./../backend/extensions:/directus/extensions
    environment:
      VIRTUAL_PORT: 8055
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      KEY: ${KEY}
      SECRET: ${SECRET}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      DB_CLIENT: ${DB_CLIENT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT_DOCKER}
      DB_DATABASE: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    depends_on:
      - {DOMAIN_NAME}-mysql
    restart: unless-stopped

  #######################################
  # Database
  #######################################
  {DOMAIN_NAME}-mysql:
    container_name: {DOMAIN_NAME}-mysql
    image: mariadb
    environment:
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=root
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - {DOMAIN_NAME}_db_data:/var/lib/mysql
    restart: unless-stopped

  #######################################
  # phpMyAdmin
  #######################################
  {DOMAIN_NAME}-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: {DOMAIN_NAME}-phpmyadmin
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=${PMA_VIRTUAL_HOST}
      - PMA_ABSOLUTE_URI=${PMA_ABSOLUTE_URI}
      - PMA_ARBITRARY=${PMA_ARBITRARY}
      - PMA_HOST=${PMA_HOST}
      - PMA_PORT=${PMA_PORT}
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    depends_on:
      - {DOMAIN_NAME}-mysql
    restart: unless-stopped

networks:
  default:
    name: dockerwp
    external: true

volumes:
  {DOMAIN_NAME}_db_data:
