version: '3.6'
services:
  #######################################
  # phpMyAdmin
  #######################################
  {DOMAIN_NAME}-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: {DOMAIN_NAME}-phpmyadmin
    depends_on:
      - {DOMAIN_NAME}-mysql
    links:
      - {DOMAIN_NAME}-mysql
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=${PMA_VIRTUAL_HOST}
      - PMA_ABSOLUTE_URI=${PMA_ABSOLUTE_URI}
      - PMA_ARBITRARY=${PMA_ARBITRARY}
      - PMA_HOST=${PMA_HOST}
      - PMA_PORT=${PMA_PORT}
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
    restart: always
    volumes:
      # Configs
      - ./../wp-docker/phpmyadmin.ini:/usr/local/etc/php/conf.d/phpmyadmin.ini

  #######################################
  # Mailhog
  #######################################
  {DOMAIN_NAME}-mail:
    image: mailhog/mailhog
    container_name: {DOMAIN_NAME}-mail
    environment:
      - VIRTUAL_PORT=8025
      - VIRTUAL_HOST=${SMTP_VIRTUAL_HOST}
    restart: always

networks:
  default:
    name: dockerwp
    external: true
