version: '3.6'
services:
  #######################################
  # phpMyAdmin
  #######################################
  {DOMAIN_NAME}-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: {DOMAIN_NAME}-phpmyadmin
    depends_on:
      - {DOMAIN_NAME}-mysql
    links:
      - {DOMAIN_NAME}-mysql
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=${PMA_VIRTUAL_HOST}
      - PMA_ABSOLUTE_URI=${PMA_ABSOLUTE_URI}
      - PMA_ARBITRARY=${PMA_ARBITRARY}
      - PMA_HOST=${PMA_HOST}
      - PMA_PORT=${PMA_PORT}
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}

networks:
  default:
    name: dockerwp
    external: true

volumes:
  {DOMAIN_NAME}_db_data:
