CREATE TABLE IF NOT EXISTS instances (
  id INT AUTO_INCREMENT PRIMARY KEY,
  PORT INT UNIQUE,
  STATUS VARCHAR(50),
  DOMAIN_NAME VARCHAR(255),
  DOMAIN_FULL VARCHAR(255),
  DB_NAME VARCHAR(255),
  DB_TYPE VARCHAR(50),
  PROJECT_TYPE VARCHAR(50),
  PORT_FRONT INT
);
