CREATE TABLE IF NOT EXISTS settings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  CORE_VERSION VARCHAR(50),
  ALIAS_CMD VARCHAR(50),
  ENV_VERSION INT,
  ENV_THEME VARCHAR(50) DEFAULT 'dark',
  ENV_DATE_CHECK DATE DEFAULT '2023-06-29'
);
